spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: true
      connection-timeout: 15000
      idle-timeout: 300000
      max-lifetime: 1800000
      maximum-pool-size: 10
      minimum-idle: 5
      pool-name: user-mgmt-mapstore
    password: superdooper
    url:  jdbc:postgresql://localhost:5432/MyDatabase
    username: admin
  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
