{{- if .Values.mancenter.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ include "mancenter.fullname" . }}"
  labels:
    app.kubernetes.io/name: {{ template "mancenter.name" . }}
    helm.sh/chart: {{ template "hazelcast.chart" . }}
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: {{ .Values.mancenter.contextPath }}/$1
    #nginx.ingress.kubernetes.io/app-root: {{ .Values.mancenter.contextPath }}
    nginx.ingress.kubernetes.io/whitelist-source-range: "0.0.0.0/0"
spec:
  tls:
    - hosts:
        - {{ if .Values.comodoHostPrefix }}{{ .Values.comodoHostPrefix }}-{{ end }}{{ .Values.tenant }}-api.optum.com
      secretName: {{ if .Values.comodoHostPrefix }}{{ .Values.comodoHostPrefix }}-{{ end }}{{ .Values.tenant }}-api-ingress-tls
  rules:
    - host: {{ if .Values.comodoHostPrefix }}{{ .Values.comodoHostPrefix }}-{{ end }}{{ .Values.tenant }}-api.optum.com
      http:
        paths:
          - path: /{{ .Values.mancenter.ingress.urlAbbrev }}/(.*)
            pathType: Prefix
            backend:
              service:
                name: {{ template "mancenter.name" . }}
                port:
                  name: http
{{- end }}
