apiVersion: v1
kind: Secret
metadata:
  name: {{ template "hazelcast.fullname" . }}-mapstore-secrets
  labels:
    app.kubernetes.io/name: {{ template "hazelcast.name" . }}
    helm.sh/chart: {{ template "hazelcast.chart" . }}
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
stringData:
  {{- range $key, $value := .Values.secrets }}
  {{ $key | upper }}: {{ $value }}
  {{- end }}
